//
//  RegionNews.swift
//  WeNews
//
//  Created by ENB Mac Mini M1 on 20/11/24.
//

import Foundation

enum RegionNews: String, Equatable {
    case unitedStates = "US"
    case taiwan = "TW"
    case german = "DE"
    case unitedKingdom = "GB"
    case china = "CN"
    case india = "IN"
    case spain = "ES"
    case italy = "IT"
    case poland = "PL"
    case australia = "AU"
    case malaysia = "MY"
    case singapore = "SG"
    case canada = "CA"
    case southKorea = "KR"
    case denmark = "DK"
    case france = "FR"
    case belgium = "BE"
    case japan = "JP"
    case austria = "AT"
    case portugal = "PT"
    case philippines = "PH"
    case hongKong = "HK"
    case argentina = "AR"
    case venezuela = "VE"
    case brazil = "BR"
    case finland = "FI"
    case indonedia = "ID"
    case vietnam = "VN"
    case mexico = "MX"
    case greece = "GR"
    case netherlands = "NL"
    case norway = "NO"
    case newZealand = "NZ"
    case russia = "RU"
    case saudiArabia = "SA"
    case switzerland = "CH"
    case thailand = "TH"
    case unitedArabEmirates = "AE"
    case ireland = "IE"
    case iran = "IR"
    case iraq = "IQ"
    case romania = "RO"
    case afghanistan = "AF"
    case zimbabwe = "ZW"
    case myanmar = "MM"
    case sweden = "SE"
    case peru = "PE"
    case panama = "PA"
    case egypt = "EG"
    case turkey = "TR"
    case israel = "IL"
    case czechRepublic = "CZ"
    case bangladesh = "BD"
    case nigeria = "NG"
    case kenya = "KE"
    case chile = "CL"
    case uruguay = "UY"
    case ecuador = "EC"
    case serbia = "RS"
    case hungary = "HU"
    case slovenia = "SI"
    case gahana = "GH"
    case bolivia = "BO"
    case pakistan = "PK"
    case colombia = "CO"
    case northKorea = "NK"
    case paraguay = "PY"
    case palestine = "PS"
    case estonia = "EE"
    case lebanon = "LB"
    case qatar = "QA"
    case kuwait = "KW"
    case cambodia = "KH"
    case nepal = "NP"
    case luxembourg = "LU"
    case bosnia = "BA"
    case europe = "EU"
    case asia = "ASIA"
    case international = "INT"
}
