def main_pods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'DeviceKit'
  pod 'Kingfisher'
end

def testing_pods
  pod 'RxBlocking'
  pod 'RxTest'
end


# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'WeNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeNews
  main_pods

end



post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
    end
  end
end
